package bookingbugAPI2.api;

import org.junit.*;
import static org.junit.Assert.*;

import java.net.MalformedURLException;
import java.net.URL;


/**
 * Testing that the urls generated by the PublicURLs class are not null and not malformed.
 * (Also testing that the configuration is loaded properly)
 */
public class PublicURLSTest {

	private static final int CompanyId = 10;


	@Test
	public void companyDetails(){
		try {
			URL url = new URL(PublicURLS.Details.companyDetails().set("companyId", CompanyId).expand());
			assertTrue(url.toString().contains(PublicURLS.Details.companyLink));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
	}


	@Test
	public void eventGroupList(){
		try {
			URL url = new URL(PublicURLS.EventGroup.eventGroupList().set("companyId", CompanyId).expand());
			assertTrue(url.toString().contains(PublicURLS.EventGroup.eventGroupsLink));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
	}


	@Test
	public void eventList(){
		try {
			URL url = new URL(PublicURLS.Event.eventList().set("companyId", CompanyId).expand());
			assertTrue(url.toString().contains(PublicURLS.Event.eventsLink));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
	}


	@Test
	public void eventRead(){
		try {
			URL url = new URL(PublicURLS.Event.eventRead().set("companyId", CompanyId).expand());
			assertTrue(url.toString().contains(PublicURLS.Event.eventsLink));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
	}


	@Test
	public void eventChainList(){
		try {
			URL url = new URL(PublicURLS.EventChain.eventChainList().set("companyId", CompanyId).expand());
			assertTrue(url.toString().contains(PublicURLS.EventChain.eventChainsLink));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
	}

}
